### ISSUE TITLE
Problem in train.sh 

### ISSUE THREAD

**Issue by HardikArora17** [fe1ixxu/BiBERT#2]
Hi , I am getting the following error while trying to run the code on google colab. Could you please help me resolve it ?

![image](https://user-images.githubusercontent.com/54908862/174546817-a98282bc-5ac6-493d-a7bb-3122ec68ea8e.png)

**Comment by fe1ixxu** [comment]
Hi, thanks for the interest in our paper. I run the script smoothly and can't reproduce the same issue. Try `pip install metadata`?

**Comment by HardikArora17** [comment]
Hi @fe1ixxu , I am still getting the same error while running. Could you have a look at it ?
Here's the  link to the notebook : https://colab.research.google.com/drive/1eMVVNhBGRIHp7WbZ6679T326RcOm-A6p?usp=sharing

Thanks for the help !

**Comment by fe1ixxu** [comment]
> Hi @fe1ixxu , I am still getting the same error while running. Could you have a look at it ? Here's the link to the notebook : https://colab.research.google.com/drive/1eMVVNhBGRIHp7WbZ6679T326RcOm-A6p?usp=sharing
> 
> Thanks for the help !

Hi, sorry for the delay. I don't have the access to the link (maybe expired). If you still have the issue, could you please share the link again and I will take a look sometime today?

**Comment by HardikArora17** [comment]
@fe1ixxu  can you please check with this link :    
https://colab.research.google.com/drive/1eMVVNhBGRIHp7WbZ6679T326RcOm-A6p?usp=sharing

**Comment by fe1ixxu** [comment]
No I still can't (this is the same link you have shared). But it looks like an env issue that not happens to everyone. Maybe try reinstall the virtual env?
<img width="762" alt="Screen Shot 2022-06-25 at 11 27 29 AM" src="https://user-images.githubusercontent.com/45837851/175786073-20729b66-8728-4e78-be58-eadba689c9ea.png">

**Comment by HardikArora17** [comment]
Hi @fe1ixxu ,The issue somehow got sorted ,you were right there was an environment issue ,thanks for helping me out . I am closing the issue now .
